export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ADMIN_ROUTE = '/bankemploee'
export const MAIN_ROUTE = '/'
export const VACANCIES_ROUTE = '/vacancies'
export const APPLICATION_ROUTE = '/application'
